all:
  children:
    vms:
      hosts:
        nas:
        lab:
        coder:
      children:
        k3s-cluster:
          children:
            k3s-servers:
              hosts:
                k3s-server-1:
                k3s-server-2:
                k3s-server-3:
            k3s-agents:
              hosts:
                k3s-agent-1:
                k3s-agent-2:
                k3s-agent-3: